## pytorch getting started
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
from __future__ import print_function

import torch

In [11]:
x = torch.empty(5, 3)

x

tensor([[-6.8950e+27,  4.5720e-41, -6.8950e+27],
        [ 4.5720e-41,  2.2705e-01,  7.2974e-01],
        [ 8.0462e-01,  7.2471e-01,  6.9550e-02],
        [ 6.3500e-01,  3.3174e-02,  7.0366e-01],
        [ 9.7294e-01,  7.0330e-01,  7.0387e-01]])

In [10]:
y = torch.rand(5, 3)

y

tensor([[0.1080, 0.0735, 0.0173],
        [0.4415, 0.2270, 0.7297],
        [0.8046, 0.7247, 0.0695],
        [0.6350, 0.0332, 0.7037],
        [0.9729, 0.7033, 0.7039]])

In [6]:
y.size()

torch.Size([5, 3])

In [12]:
x + y

tensor([[-6.8950e+27,  7.3508e-02, -6.8950e+27],
        [ 4.4145e-01,  4.5409e-01,  1.4595e+00],
        [ 1.6092e+00,  1.4494e+00,  1.3910e-01],
        [ 1.2700e+00,  6.6349e-02,  1.4073e+00],
        [ 1.9459e+00,  1.4066e+00,  1.4077e+00]])

In [13]:
torch.add(x, y)

tensor([[-6.8950e+27,  7.3508e-02, -6.8950e+27],
        [ 4.4145e-01,  4.5409e-01,  1.4595e+00],
        [ 1.6092e+00,  1.4494e+00,  1.3910e-01],
        [ 1.2700e+00,  6.6349e-02,  1.4073e+00],
        [ 1.9459e+00,  1.4066e+00,  1.4077e+00]])

In [18]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)

result

tensor([[-6.8950e+27,  7.3508e-02, -6.8950e+27],
        [ 4.4145e-01,  4.5409e-01,  1.4595e+00],
        [ 1.6092e+00,  1.4494e+00,  1.3910e-01],
        [ 1.2700e+00,  6.6349e-02,  1.4073e+00],
        [ 1.9459e+00,  1.4066e+00,  1.4077e+00]])

In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [21]:
x.numpy()

array([[-0.71466774, -0.4841901 ,  0.73054874, -1.4817328 ],
       [-2.3562214 ,  0.7825239 ,  1.6976838 ,  0.64681125],
       [ 0.6689326 ,  0.21224383, -1.4699931 , -0.6023307 ],
       [ 0.77160865, -0.1966304 ,  1.1696484 , -0.12227216]],
      dtype=float32)

In [22]:
import numpy as np

a = np.ones(5)
torch.from_numpy(a)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)